# global config
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: 'service_database_metrics'
    static_configs:
      - targets: ['service_database:5003']
  - job_name: 'service_api_gateway_metrics'
    static_configs:
      - targets: [ 'service_api_gateway:5005' ]